const topicNames=[['Percentages','Quantitative','%'],['Profit & Loss','Quantitative','₹'],['Simple Interest','Quantitative','↗'],['Compound Interest','Quantitative','◒'],['Ratio & Proportion','Quantitative','∶'],['Partnership','Quantitative','♧'],['Averages','Quantitative','x̄'],['Mixture & Alligation','Quantitative','⚗'],['Time & Work','Quantitative','◷'],['Pipes & Cisterns','Quantitative','⌇'],['Time, Speed & Distance','Quantitative','➜'],['Boats & Streams','Quantitative','≋'],['Trains','Quantitative','▰'],['Problems on Ages','Quantitative','♙'],['Calendar','Logical','▦'],['Clocks','Logical','◷'],['Permutation','Quantitative','P'],['Combination','Quantitative','C'],['Probability','Quantitative','◉'],['Number System','Quantitative','#'],['HCF & LCM','Quantitative','×'],['Divisibility','Quantitative','÷'],['Simplification','Quantitative','='],['Surds & Indices','Quantitative','√'],['Logarithms','Quantitative','log'],['Algebra','Quantitative','x'],['Geometry','Quantitative','△'],['Mensuration','Quantitative','▱'],['Data Interpretation','Data','▥'],['Data Sufficiency','Data','?'],['Venn Diagrams','Logical','◯'],['Blood Relations','Logical','♧'],['Direction Sense','Logical','⌖'],['Coding–Decoding','Logical','</>'],['Series','Logical','∿'],['Analogy','Logical','≈'],['Classification','Logical','⊞'],['Ranking','Logical','№'],['Seating Arrangement','Logical','◌'],['Puzzle Solving','Logical','◇'],['Logical Reasoning','Logical','∴'],['Verbal Reasoning','Verbal','Aa'],['Non-Verbal Reasoning','Logical','◈'],['Critical Reasoning','Verbal','!'],['Quantitative Aptitude','Quantitative','∑'],['Arithmetic','Quantitative','+'],['Modern Math','Quantitative','∞'],['Basic Statistics','Data','σ'],['Quadratic Equations','Quantitative','x²'],['Frequently Asked','All','★']];
const descriptions={Quantitative:'Concepts, formulas, shortcuts & placement drills',Logical:'Patterns, deductions & smart reasoning',Verbal:'Arguments, language & critical thinking',Data:'Charts, tables & analytical decisions',All:'High-frequency placement essentials'};
const formulas={
 'Percentages':['Percentage = (Part ÷ Whole) × 100','Successive change = a + b + ab/100','New value = Original × (100 ± r)/100'],
 'Profit & Loss':['Profit% = Profit ÷ CP × 100','SP = CP × (100 + Profit%)/100','Discount% = Discount ÷ MP × 100'],
 'Time & Work':['Work = Rate × Time','Combined rate = 1/a + 1/b','Efficiency ∝ 1/Time'],
 'Time, Speed & Distance':['Distance = Speed × Time','Relative speed: add (opposite), subtract (same)','Average speed (equal distance) = 2xy/(x+y)'],
 'Probability':['P(E) = Favourable outcomes ÷ Total outcomes','P(not E) = 1 − P(E)','P(A∪B)=P(A)+P(B)−P(A∩B)'],
 'Averages':['Average = Sum of observations ÷ Count','Combined average = (n₁a₁+n₂a₂)/(n₁+n₂)']
};
const state=JSON.parse(localStorage.getItem('aptitudeXState')||'{"completed":[],"bookmarks":[],"tests":0,"theme":"light"}');
state.questionResults=state.questionResults||{};state.reviewQuestions=state.reviewQuestions||[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('aptitudeXState',JSON.stringify(state))}
function colorFor(cat){return cat==='Logical'?'mint':cat==='Verbal'?'orange':cat==='Data'?'blue':'purple'}
function progressFor(name,i){return state.completed.includes(name)?100:[0,42,68,25][i%4]}
function renderTopics(category='All',all=false){const grid=$('#topicsGrid');const items=topicNames.filter(t=>category==='All'||t[1]===category).slice(0,all?50:8);grid.innerHTML=items.map((t,i)=>`<article class="topic-card" tabindex="0" data-topic="${t[0]}"><span class="topic-icon ${colorFor(t[1])}">${t[2]}</span><h3>${t[0]}</h3><p>${descriptions[t[1]]}</p><footer><span>${8+i%7} lessons · ${40+i*3} questions</span><b>${progressFor(t[0],i)}%</b></footer><div class="progress-line"><i style="width:${progressFor(t[0],i)}%"></i></div></article>`).join('');
  $$('.topic-card').forEach(c=>{c.onclick=()=>openTopic(c.dataset.topic);c.onkeydown=e=>{if(e.key==='Enter')openTopic(c.dataset.topic)}})
}
function openModal(el){el.hidden=false;document.body.classList.add('modal-open')}
function closeModal(el){el.hidden=true;document.body.classList.remove('modal-open')}
function openTopic(name){const t=topicNames.find(x=>x[0]===name), fs=formulas[name]||genericFormulas(name);$('#topicTitle').textContent=name;$('#topicCategory').textContent=t[1]+' · Complete lesson';$('#topicContent').innerHTML=`<div class="detail-hero"><section class="detail-card"><h3>Why this matters</h3><p>${name} is a core aptitude skill used to test calculation accuracy, structured thinking, and decision-making under time pressure. Recruiters expect you to recognize patterns and choose the shortest valid method.</p><h3>Smart solving approach</h3><ul><li>Translate the question into known values.</li><li>Estimate before calculating to eliminate options.</li><li>Use ratios or fractions when they reduce arithmetic.</li><li>Check units and the required base value.</li></ul></section><section class="detail-card"><h3>Lesson map</h3><p>1. Foundations<br>2. Formula toolkit<br>3. Shortcut methods<br>4. Solved examples<br>5. Placement drill</p><p><strong>Difficulty:</strong> Beginner → Placement</p><p><strong>Expected time:</strong> 2–4 min/question</p></section></div><h3>Essential formula sheet</h3>${fs.map((f,i)=>`<div class="formula-card"><small>FORMULA ${i+1}</small><code>${f}</code><p>Use this after identifying the base quantities. Avoid applying it before confirming that units and reference values match.</p></div>`).join('')}<div class="detail-card"><h3>Solved example</h3><p><strong>Question:</strong> A value changes from 80 to 100. Find the percentage increase.</p><p><strong>Step 1:</strong> Change = 100 − 80 = 20<br><strong>Step 2:</strong> Use the original value as the base.<br><strong>Step 3:</strong> Increase = (20/80) × 100 = <strong>25%</strong>.</p><p><strong>Shortcut:</strong> 20 is one-fourth of 80, so the increase is immediately 25%.</p></div><div class="lesson-actions"><button class="button primary complete-topic" data-name="${name}">${state.completed.includes(name)?'Completed ✓':'Mark lesson complete'}</button><button class="button secondary bookmark-topic" data-name="${name}">${state.bookmarks.includes(name)?'★ Saved':'☆ Bookmark'}</button></div>`;openModal($('#topicModal'));bindLessonActions()}
function genericFormulas(name){return [`Core relation for ${name}: Result = Known values × Required ratio`,'Percentage comparison = Difference ÷ Reference × 100','Weighted result = Σ(value × weight) ÷ Σ(weights)']}
function bindLessonActions(){$('.complete-topic').onclick=e=>{const n=e.currentTarget.dataset.name;if(!state.completed.includes(n))state.completed.push(n);save();e.currentTarget.textContent='Completed ✓';renderTopics($('.topic-tabs .active').dataset.category,$('#viewAllTopics').dataset.all==='true');toast('Progress saved — nice work!')};$('.bookmark-topic').onclick=e=>{const n=e.currentTarget.dataset.name;state.bookmarks.includes(n)?state.bookmarks.splice(state.bookmarks.indexOf(n),1):state.bookmarks.push(n);save();e.currentTarget.textContent=state.bookmarks.includes(n)?'★ Saved':'☆ Bookmark';toast(state.bookmarks.includes(n)?'Topic bookmarked':'Bookmark removed')}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
renderTopics();document.documentElement.dataset.theme=state.theme;$('#themeToggle').textContent=state.theme==='dark'?'☀':'☾';
$$('.topic-tabs button').forEach(b=>b.onclick=()=>{$$('.topic-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTopics(b.dataset.category,$('#viewAllTopics').dataset.all==='true')});
$('#viewAllTopics').onclick=e=>{e.preventDefault();e.currentTarget.dataset.all='true';e.currentTarget.textContent='Showing all 50 topics';renderTopics($('.topic-tabs .active').dataset.category,true)};
$('#themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;$('#themeToggle').textContent=state.theme==='dark'?'☀':'☾';save()};
$('#menuToggle').onclick=()=>$('.desktop-nav').classList.toggle('open');$$('.desktop-nav a').forEach(a=>a.onclick=()=>$('.desktop-nav').classList.remove('open'));
$('#searchOpen').onclick=()=>{openModal($('#searchModal'));setTimeout(()=>$('#globalSearch').focus(),50);showSearch('')};
function showSearch(q){const filtered=topicNames.filter(t=>t.join(' ').toLowerCase().includes(q.toLowerCase())).slice(0,9);$('#searchResults').innerHTML=filtered.length?filtered.map(t=>`<div class="search-result" tabindex="0" data-topic="${t[0]}"><strong>${t[2]} &nbsp; ${t[0]}</strong><small>${t[1]} · Lessons, formulas and practice</small></div>`).join(''):'<p>No results found. Try a topic or category.</p>';$$('.search-result').forEach(x=>x.onclick=()=>{closeModal($('#searchModal'));openTopic(x.dataset.topic)})}
$('#globalSearch').oninput=e=>showSearch(e.target.value);
$$('.modal-close').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal')));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m)});document.onkeydown=e=>{if(e.key==='Escape')$$('.modal:not([hidden])').forEach(closeModal)};
$('#dailyOptions').onclick=e=>{const btn=e.target.closest('button');if(!btn)return;$$('#dailyOptions button').forEach(b=>{b.disabled=true;if(b.dataset.answer==='19')b.classList.add('correct')});if(btn.dataset.answer!=='19')btn.classList.add('wrong');$('#answerFeedback').textContent=btn.dataset.answer==='19'?'Correct! 1.40 × 0.85 = 1.19, so profit is 19%.':'Not quite. Apply discount to marked price: 1.40 × 0.85 = 1.19.'};
let seconds=60;const timerInt=setInterval(()=>{if(seconds<=0){clearInterval(timerInt);return}seconds--;$('#timer').textContent=`00:${String(seconds).padStart(2,'0')}`},1000);
function startTest(name){
  let pool=(window.questionBank||[]).filter(q=>q.sourceBook&&q.answer);
  if(name==='Quantitative Sprint')pool=pool.filter(q=>!['Series','Direction Sense','Coding–Decoding','Verbal Reasoning'].includes(q.topic));
  if(name==='Logical Reasoning')pool=pool.filter(q=>['Series','Direction Sense','Coding–Decoding','Probability'].includes(q.topic));
  const quiz=[...pool].sort(()=>Math.random()-.5).slice(0,20).map(q=>({q:q.question,o:q.options,a:q.options.indexOf(q.answer),solution:q.solution}));
  let idx=0,score=0,review=[];$('#testTitle').textContent=name;openModal($('#testModal'));
  function draw(){
    const x=quiz[idx], options=x.o.map((o,i)=>`<button data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('');
    $('#testContent').innerHTML=`<div class="test-status"><span>Question ${idx+1} of ${quiz.length}</span><span>20-question timed assessment</span></div><div class="quiz-question"><h3>${x.q}</h3><div class="quiz-options">${options}</div><div class="lesson-actions"><button class="button primary" id="nextQuestion" disabled>${idx===quiz.length-1?'Finish test':'Next question →'}</button></div></div>`;
    let selected=null;
    $$('.quiz-options button').forEach(b=>b.onclick=()=>{$$('.quiz-options button').forEach(y=>y.classList.remove('selected'));b.classList.add('selected');selected=+b.dataset.i;$('#nextQuestion').disabled=false});
    $('#nextQuestion').onclick=()=>{if(selected===x.a)score++;else review.push({q:x.q,answer:x.o[x.a]||'Not keyed',solution:x.solution});idx++;if(idx<quiz.length)draw();else finish()};
  }
  function finish(){
    state.tests++;save();const percent=Math.round(score/quiz.length*100);
    $('#testContent').innerHTML='<div class="test-result"><small>TEST COMPLETE</small><br><strong>'+score+'/'+quiz.length+'</strong><h3>'+(percent>=80?'Excellent work!':'Good attempt—keep practicing.')+'</h3><p>You scored '+percent+'%. '+review.length+' questions need review.</p></div>'+review.slice(0,5).map((r,i)=>'<div class="detail-card"><h3>Review '+(i+1)+'</h3><p>'+escapeHtml(r.q)+'</p><p><strong>Answer:</strong> '+escapeHtml(r.answer)+'<br><strong>Solution:</strong> '+escapeHtml(r.solution)+'</p></div>').join('')+'<div class="lesson-actions"><button class="button primary" id="closeResult">Back to dashboard</button></div>';
    $('#closeResult').onclick=()=>closeModal($('#testModal'));
  }
  draw();
}
$$('.start-test').forEach(b=>b.onclick=()=>startTest(b.dataset.test));$('#profileButton').onclick=()=>toast(`${state.completed.length} topics completed · ${state.tests} tests taken · ${state.bookmarks.length} saved`);
const sections=$$('main section[id]');window.addEventListener('scroll',()=>{let current='home';sections.forEach(s=>{if(scrollY>=s.offsetTop-150)current=s.id});$$('.desktop-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))},{passive:true});

// Master question bank: filters, pagination, instant checking and persistent accuracy.
let bankPage=1,bankMode=null;const bankPageSize=10,bank=window.questionBank||[];
const bankTopics=[...new Set(bank.map(q=>q.topic))].sort();$('#questionTopic').innerHTML+=bankTopics.map(t=>`<option>${t}</option>`).join('');$('#questionModel').innerHTML+=[...new Set(bank.map(q=>q.model))].map(t=>`<option>${t}</option>`).join('');$('#bankTotal').textContent=bank.length+'+';
function filteredBank(){if(bankMode)return bankMode;const term=$('#questionSearch').value.trim().toLowerCase(),topic=$('#questionTopic').value,kind=$('#questionKind').value,model=$('#questionModel').value,diff=$('#questionDifficulty').value,company=$('#questionCompany').value;return bank.filter(q=>(topic==='All'||q.topic===topic)&&(kind==='All'||q.kind===kind)&&(model==='All'||q.model===model)&&(diff==='All'||q.difficulty===diff)&&(company==='All'||q.company===company)&&(!term||(q.question+' '+q.topic+' '+q.model+' '+q.solution).toLowerCase().includes(term)))}
function renderBank(){const rows=filteredBank(),pages=Math.max(1,Math.ceil(rows.length/bankPageSize));bankPage=Math.min(bankPage,pages);const shown=rows.slice((bankPage-1)*bankPageSize,bankPage*bankPageSize);$('#bankResultLabel').textContent=`${rows.length} questions found${bankMode?' · focused drill':''}`;$('#bankPage').textContent=`${bankPage} / ${pages}`;$('#prevBank').disabled=bankPage<=1;$('#nextBank').disabled=bankPage>=pages;$('#questionList').innerHTML=shown.length?shown.map(q=>questionHTML(q)).join(''):'<div class="detail-card"><h3>No questions found</h3><p>Change one or more filters and try again.</p></div>';bindBank();updateBankStats()}
function escapeHtml(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function stepList(q){return `<ol class="solution-steps">${(q.steps||[q.solution]).map((s,i)=>`<li><span>Step ${i+1}</span>${escapeHtml(s)}</li>`).join('')}</ol>`}
function questionHTML(q){const previous=state.questionResults[q.id],example=q.kind==='Solved Example';return `<article class="question-item" data-id="${q.id}"><div class="question-tags"><span class="level">${q.difficulty}</span><span>${q.kind}</span><span>${q.topic}</span><span class="model-tag">Model: ${q.model||'Placement model'}</span><span>${q.company} pattern</span><span>⏱ ${q.time}s</span></div><h3>${q.id}. ${q.question}</h3><div class="bank-options">${q.options.map((o,i)=>`<button data-option="${escapeAttr(o)}" ${previous?'disabled':''} class="${previous?(o===q.answer?'correct':previous.answer===o&&!previous.correct?'wrong':''):''}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div class="question-actions">${example?'<button class="hint-question">💡 Hint</button><button class="solution-question">▤ Worked solution</button>':''}<button class="review-question">${state.reviewQuestions.includes(q.id)?'★ Review saved':'☆ Save for review'}</button></div><div class="question-explanation ${example?'show':''}">${example?`<p class="hint-text" hidden><strong>Hint:</strong> ${escapeHtml(q.hint)}</p><div class="solution-text"><strong>Worked solution</strong>${stepList(q)}<p><strong>Shortcut:</strong> ${escapeHtml(q.shortcut)}</p></div>`:'<p class="practice-note" hidden><strong>Answer submitted.</strong> The solution remains hidden in practice mode.</p>'}</div></article>`}
function escapeAttr(v){return String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;')}
function bindBank(){$$('.question-item').forEach(card=>{const q=bank.find(x=>x.id===+card.dataset.id),buttons=[...card.querySelectorAll('.bank-options button')];buttons.forEach(btn=>btn.onclick=()=>{const correct=btn.dataset.option===q.answer;state.questionResults[q.id]={answer:btn.dataset.option,correct};save();buttons.forEach(b=>{b.disabled=true;if(b.dataset.option===q.answer)b.classList.add('correct')});if(!correct)btn.classList.add('wrong');const exp=card.querySelector('.question-explanation'),sol=card.querySelector('.solution-text'),note=card.querySelector('.practice-note');exp.classList.add('show');if(sol)sol.hidden=false;if(note)note.hidden=false;updateBankStats();toast(correct?'Correct — well solved!':q.kind==='Practice'?'Answer recorded — solution remains hidden.':'Review the worked solution below.')});const hintBtn=card.querySelector('.hint-question'),solutionBtn=card.querySelector('.solution-question');if(hintBtn)hintBtn.onclick=()=>{const exp=card.querySelector('.question-explanation'),hint=card.querySelector('.hint-text');exp.classList.add('show');hint.hidden=!hint.hidden};if(solutionBtn)solutionBtn.onclick=()=>{const exp=card.querySelector('.question-explanation'),sol=card.querySelector('.solution-text');exp.classList.add('show');sol.hidden=!sol.hidden};card.querySelector('.review-question').onclick=e=>{const at=state.reviewQuestions.indexOf(q.id);at>=0?state.reviewQuestions.splice(at,1):state.reviewQuestions.push(q.id);save();e.currentTarget.textContent=at>=0?'☆ Save for review':'★ Review saved'}})}
function updateBankStats(){const vals=Object.values(state.questionResults),correct=vals.filter(x=>x.correct).length;$('#solvedCount').textContent=vals.length;$('#accuracyCount').textContent=vals.length?Math.round(correct/vals.length*100)+'%':'0%'}
['questionSearch','questionTopic','questionKind','questionModel','questionDifficulty','questionCompany'].forEach(id=>$('#'+id).addEventListener(id==='questionSearch'?'input':'change',()=>{bankMode=null;bankPage=1;renderBank()}));$('#prevBank').onclick=()=>{bankPage--;renderBank();$('#question-bank').scrollIntoView()};$('#nextBank').onclick=()=>{bankPage++;renderBank();$('#question-bank').scrollIntoView()};$('#randomPractice').onclick=()=>{bankMode=bank.filter(q=>q.answer).sort(()=>Math.random()-.5).slice(0,20);bankPage=1;renderBank();toast('20-question mixed drill ready')};renderBank();

const extendedFormulas={
'Compound Interest':['Amount = P(1+r/100)^n','CI = Amount − Principal','For 2 years: CI−SI = P(r/100)²'],'Ratio & Proportion':['a:b = a/b','If a:b=c:d, then ad=bc','Fourth proportional d=bc/a'],'Partnership':['Profit share ∝ Capital × Time'],'Mixture & Alligation':['Mean price = Total cost/Total quantity','Cheaper:Dearer = (Dearer−Mean):(Mean−Cheaper)','Remaining concentration = Initial(1−removed/volume)^n'],'Pipes & Cisterns':['Net rate = Sum of inlet rates − Sum of outlet rates','Time = 1/Net rate'],'Boats & Streams':['Downstream=b+s','Upstream=b−s','Boat=(D+U)/2; Stream=(D−U)/2'],'Trains':['Pole time = Train length/speed','Platform time = (Train+Platform length)/speed','Relative speed: sum opposite, difference same'],'Problems on Ages':['Future age = Present+n','Past age = Present−n'],'Calendar':['Odd days = Total days mod 7','Leap year: divisible by 4, except centuries not divisible by 400'],'Clocks':['Angle = |30H−5.5M|','Minute hand speed=6°/min; hour hand=0.5°/min'],'Permutation':['nPr=n!/(n−r)!','Circular arrangements=(n−1)!','Repeated objects=n!/(p!q!...)'],'Combination':['nCr=n!/[r!(n−r)!]','nCr=nC(n−r)'],'Number System':['Dividend=Divisor×Quotient+Remainder','Sum 1..n=n(n+1)/2','Sum squares=n(n+1)(2n+1)/6'],'HCF & LCM':['HCF×LCM=Product of two numbers','LCM takes highest prime powers; HCF lowest'],'Divisibility':['3/9: digit sum test','4: last 2 digits; 8: last 3 digits','11: alternating digit-sum difference'],'Simplification':['BODMAS: Brackets, Orders, Division, Multiplication, Addition, Subtraction'],'Surds & Indices':['a^m×a^n=a^(m+n)','a^m/a^n=a^(m−n)','√ab=√a√b'],'Logarithms':['log(ab)=log a+log b','log(a/b)=log a−log b','log(a^n)=n log a'],'Algebra':['(a+b)²=a²+2ab+b²','a²−b²=(a−b)(a+b)','Linear equation ax+b=c ⇒ x=(c−b)/a'],'Quadratic Equations':['x=[−b±√(b²−4ac)]/2a','Sum of roots=−b/a','Product of roots=c/a'],'Geometry':['Triangle angle sum=180°','Triangle area=½bh','Heron area=√[s(s−a)(s−b)(s−c)]'],'Mensuration':['Rectangle A=lb; P=2(l+b)','Circle A=πr²; C=2πr','Cylinder V=πr²h; Sphere V=4πr³/3'],'Data Interpretation':['Percentage change=(New−Old)/Old×100','Weighted mean=Σwx/Σw'],'Data Sufficiency':['Test statement I and II independently before combining'],'Venn Diagrams':['n(A∪B)=n(A)+n(B)−n(A∩B)'],'Ranking':['Opposite rank=Total−Known rank+1'],'Seating Arrangement':['Circular arrangements=(n−1)!'],'Series':['Check differences, second differences, ratios and alternating terms'],'Basic Statistics':['Mean=Σx/n','Median=Middle ordered value','Variance=Σ(x−mean)²/n'],'Probability':['P(E)=Favourable/Total','P(not E)=1−P(E)','P(A∪B)=P(A)+P(B)−P(A∩B)'],'Modern Math':['n(A∪B)=n(A)+n(B)−n(A∩B)','AP nth term=a+(n−1)d','AP sum=n[2a+(n−1)d]/2'],'Arithmetic':['Sum 1..n=n(n+1)/2','Average=Sum/Count'],'Direction Sense':['Displacement=√(x²+y²)'],'Quantitative Aptitude':['Work=Rate×Time','Distance=Speed×Time','Percentage=Part/Whole×100']};
Object.assign(formulas,extendedFormulas);
Object.assign(formulas,{'Blood Relations':['Generation: parent +1, child −1, sibling 0','Track gender and perspective separately'],'Coding–Decoding':['Forward shift=(old position+k) mod 26','Reverse shift=(old position−k) mod 26'],'Analogy':['A:B :: C:D means relation(A,B)=relation(C,D)'],'Classification':['Odd item does not share the defining property'],'Puzzle Solving':['Translate each clue into one constraint before combining'],'Logical Reasoning':['All A are B means A is a subset of B; the converse is not guaranteed','Some A are B means their intersection is non-empty'],'Verbal Reasoning':['Subject and verb agree in number','Parallel items share grammatical form'],'Non-Verbal Reasoning':['Track shape, count, rotation, position and shading independently'],'Critical Reasoning':['Conclusion strength cannot exceed evidence','Correlation does not establish causation'],'Frequently Asked':['Successive change=a+b+ab/100','Equal-distance average speed=2xy/(x+y)']});
openTopic=function(name){const t=topicNames.find(x=>x[0]===name)||[name,'Aptitude'],fs=formulas[name]||genericFormulas(name),items=bank.filter(q=>q.topic===name),examples=items.filter(q=>q.kind==='Solved Example'),practice=items.filter(q=>q.kind==='Practice');$('#topicTitle').textContent=name;$('#topicCategory').textContent=`${t[1]} · ${examples.length} examples · ${practice.length} practice`;$('#topicContent').innerHTML=`<div class="detail-hero"><section class="detail-card"><h3>Concept and exam use</h3><p>${name} develops fast pattern recognition, accurate calculation, and structured elimination under placement-test time limits.</p><h3>Recommended method</h3><ul><li>Identify the given values and required result.</li><li>Select the shortest valid formula or reasoning rule.</li><li>Estimate to eliminate impossible options.</li><li>Verify units, base values, and hidden conditions.</li></ul></section><section class="detail-card"><h3>Topic resources</h3><p><strong>${fs.length}</strong> core formulas<br><strong>20</strong> worked examples<br><strong>20</strong> private-solution practice questions<br><strong>5</strong> difficulty bands</p></section></div><h3>Formula sheet</h3>${fs.map((f,i)=>`<div class="formula-card"><small>FORMULA / RULE ${i+1}</small><code>${f}</code><p>Use after identifying the relevant quantities. Check assumptions and units before substitution.</p></div>`).join('')}<h3>Worked-example preview</h3>${examples.slice(0,2).map((q,i)=>`<div class="detail-card"><p><strong>Example ${i+1}:</strong> ${q.question}</p><p><strong>Answer:</strong> ${q.answer}</p>${stepList(q)}<p><strong>Shortcut:</strong> ${escapeHtml(q.shortcut)}</p></div>`).join('')}<div class="lesson-actions"><button class="button primary open-topic-set" data-kind="Solved Example">Study all 20 examples</button><button class="button secondary open-topic-set" data-kind="Practice">Start 20 practice questions</button></div><div class="lesson-actions"><button class="button secondary complete-topic" data-name="${name}">${state.completed.includes(name)?'Completed ✓':'Mark topic complete'}</button><button class="button secondary bookmark-topic" data-name="${name}">${state.bookmarks.includes(name)?'★ Saved':'☆ Bookmark'}</button></div>`;openModal($('#topicModal'));bindLessonActions();$$('.open-topic-set').forEach(b=>b.onclick=()=>{closeModal($('#topicModal'));bankMode=null;$('#questionTopic').value=name;$('#questionKind').value=b.dataset.kind;$('#questionDifficulty').value='All';$('#questionCompany').value='All';$('#questionSearch').value='';bankPage=1;renderBank();$('#question-bank').scrollIntoView({behavior:'smooth'})})};
