(function(){
const levels=['Beginner','Easy','Medium','Hard','Placement'],companies=['General Placement','TCS NQT','Infosys','Wipro','Accenture','Capgemini','Cognizant'];
const bank=[];let uid=1;const gcd=(a,b)=>b?gcd(b,a%b):a,fmt=n=>Number.isInteger(+n)?String(+n):String(Math.round(+n*100)/100);
function choices(answer,step=1,suffix=''){let a=+answer;return [a,a+step,a-step,a+2*step].map(x=>fmt(x)+suffix)}
function add(topic,i,question,answer,solution,hint,options,shortcut){answer=String(answer);options=(options||choices(answer,Math.max(1,Math.round(Math.abs(+answer)*.1)))).map(String);if(!options.includes(answer))options[3]=answer;options=[...new Set(options)];while(options.length<4)options.push(String((+answer||10)+options.length));options=options.slice(0,4).sort((a,b)=>((a.charCodeAt(0)+i*3)%7)-((b.charCodeAt(0)+i*5)%7));bank.push({id:uid++,topic,difficulty:levels[(i-1)%5],company:companies[(i-1)%7],question,answer,options,solution,hint,shortcut:shortcut||'Estimate first and eliminate impossible choices.',time:45+(i%5)*15})}
for(let i=1;i<=40;i++){let p=10+(i%8)*5,n=120+i*20,a=n*p/100;add('Percentages',i,`What is ${p}% of ${n}?`,a,`${p}/100 × ${n} = ${a}.`,`Convert ${p}% to a fraction over 100.`,null,`Split ${p}% into easy 10%, 5%, and 1% chunks.`)}
for(let i=1;i<=40;i++){let cp=200+i*25,r=5+(i%6)*5,sp=cp*(100+r)/100;add('Profit & Loss',i,`An article costs ₹${cp} and is sold at ${r}% profit. Find its selling price.`,sp,`SP = CP × (100 + profit%)/100 = ${cp} × ${100+r}/100 = ₹${sp}.`,'Profit percentage uses cost price as the base.',null,`Multiply directly by ${(1+r/100).toFixed(2)}.`)}
for(let i=1;i<=40;i++){let p=1000+i*250,r=4+i%9,t=1+i%5,si=p*r*t/100;add('Simple Interest',i,`Find the simple interest on ₹${p} at ${r}% per annum for ${t} years.`,si,`SI = PRT/100 = ${p} × ${r} × ${t}/100 = ₹${si}.`,'Use SI = P × R × T ÷ 100.',null,'Cancel factors with 100 before multiplying.')}
for(let i=1;i<=40;i++){let p=1000+i*500,r=[5,10,20][i%3],ci=p*((1+r/100)**2-1);add('Compound Interest',i,`Find the compound interest on ₹${p} at ${r}% annually for 2 years.`,ci,`CI = ${p}[(1+${r}/100)²−1] = ₹${ci}.`,'Find amount after two growth periods, then subtract principal.',null,'For two years, CI = SI + P(R/100)².')}
for(let i=1;i<=40;i++){let a=2+i%5,b=3+(i*2)%6,total=(a+b)*(20+i),share=total*a/(a+b);add('Ratio & Proportion',i,`₹${total} is divided in the ratio ${a}:${b}. Find the first share.`,share,`Total parts = ${a+b}; first share = ${total} × ${a}/${a+b} = ₹${share}.`,'Add all ratio parts first.',null,'Find one part, then multiply.')}
for(let i=1;i<=40;i++){let ns=[10+i,14+i,18+i,22+i,26+i],av=ns[2];add('Averages',i,`Find the average of ${ns.join(', ')}.`,av,`The sum is ${ns.reduce((a,b)=>a+b)}. Divide by 5 to get ${av}.`,'These values are equally spaced.',null,'The middle of an arithmetic sequence is its average.')}
for(let i=1;i<=40;i++){let a=8+i%9,b=12+(i*2)%11,t=a*b/(a+b);add('Time & Work',i,`A finishes a job in ${a} days and B in ${b} days. How long do they take together?`,fmt(t),`Combined rate = 1/${a}+1/${b}. Time = ${a*b}/${a+b} = ${fmt(t)} days.`,'Add rates, not days.',choices(t,1),'For two workers, use ab/(a+b).')}
for(let i=1;i<=40;i++){let s=30+(i%8)*5,t=2+i%5,d=s*t;add('Time, Speed & Distance',i,`A vehicle travels at ${s} km/h for ${t} hours. What distance does it cover?`,d,`Distance = speed × time = ${s} × ${t} = ${d} km.`,'Use D = S × T.',null,'Confirm units before calculation.')}
for(let i=1;i<=40;i++){let l=100+i*10,sec=8+i%8,s=l/sec*3.6;add('Trains',i,`A ${l} m train crosses a pole in ${sec} seconds. Find its speed in km/h.`,fmt(s),`Speed = ${l}/${sec} = ${fmt(l/sec)} m/s = ${fmt(s)} km/h.`,'For a pole, distance equals train length.',choices(s,3.6),'Multiply m/s by 3.6.')}
for(let i=1;i<=40;i++){let son=8+i,f=2+i%4,fa=son*f;add('Problems on Ages',i,`A father is ${f} times his son's age. If the son is ${son}, find the father's age.`,fa,`Father's age = ${f} × ${son} = ${fa} years.`,'Translate “times” into multiplication.',null,'Check whether ages are present or shifted.')}
for(let i=1;i<=40;i++){let r=2+i%6,b=3+(i*2)%7,d=r+b,g=gcd(r,d),ans=`${r/g}/${d/g}`;add('Probability',i,`A bag has ${r} red and ${b} blue balls. What is the probability of drawing red?`,ans,`Favourable = ${r}; total = ${d}. P = ${r}/${d} = ${ans}.`,'Probability is favourable outcomes ÷ total.',[ans,`${b}/${d}`,`${r}/${b}`,`1/${d}`],'Simplify the final fraction.')}
for(let i=1;i<=40;i++){let a=12+i*2,b=18+i*3,h=gcd(a,b);add('HCF & LCM',i,`Find the HCF of ${a} and ${b}.`,h,`By prime factors or Euclid's method, HCF(${a}, ${b}) = ${h}.`,'Find the largest shared factor.',null,'Euclid repeatedly replaces the larger number by the remainder.')}
for(let i=1;i<=40;i++){let x=2+i%9,b=3+i%7;add('Quadratic Equations',i,`Which is a positive root of x² + ${b-x}x − ${b*x} = 0?`,x,`Substitute x=${x}: ${x*x}+${b-x}×${x}−${b*x}=0, so ${x} is a root.`,'Test integer factors of the constant.',null,'Option substitution is often faster than the quadratic formula.')}
for(let i=1;i<=40;i++){let l=8+i,b=4+i%7,a=l*b;add('Mensuration',i,`Find the area of a rectangle ${l} cm long and ${b} cm broad.`,a,`Area = l × b = ${l} × ${b} = ${a} cm².`,'Use A = length × breadth.',null,'Area always uses square units.')}
for(let i=1;i<=40;i++){let st=1+i,d=2+i%6,seq=[0,1,2,3].map(k=>st+k*d),n=st+4*d;add('Series',i,`Find the next term: ${seq.join(', ')}, ?`,n,`The common difference is ${d}; next = ${seq[3]} + ${d} = ${n}.`,'Check first differences.',null,'Subtract adjacent terms before trying complex rules.')}
for(let i=1;i<=40;i++){let e=3+i,n=4+i%5,d=Math.sqrt(e*e+n*n);add('Direction Sense',i,`Riya walks ${e} km east, then ${n} km north. How far is she from the start?`,fmt(d),`Distance = √(${e}²+${n}²) = ${fmt(d)} km.`,'Draw coordinates and use Pythagoras.',choices(d,1),'Track final x and y coordinates.')}
for(let i=1;i<=40;i++){let sh=1+i%5,w='CAT',c=[...w].map(x=>String.fromCharCode(65+(x.charCodeAt(0)-65+sh)%26)).join('');add('Coding–Decoding',i,`Every letter moves ${sh} place${sh>1?'s':''} forward. How is CAT coded?`,c,`C→${c[0]}, A→${c[1]}, T→${c[2]}; answer ${c}.`,'Apply the same shift to every letter.',[c,'CAT','DBU','ECV'],'Use alphabet positions when wrapping after Z.')}
for(let i=1;i<=40;i++){let s=[120+i*5,150+i*5,180+i*5,210+i*5],p=(s[3]-s[0])/s[0]*100;add('Data Interpretation',i,`Sales: Q1 ₹${s[0]}L, Q2 ₹${s[1]}L, Q3 ₹${s[2]}L, Q4 ₹${s[3]}L. Percentage increase from Q1 to Q4?`,fmt(p),`Increase = ${s[3]-s[0]}. Increase% = ${s[3]-s[0]}/${s[0]} × 100 = ${fmt(p)}%.`,'Q1 is the reference base.',choices(p,5),'Estimate the fraction before exact division.')}
for(let i=1;i<=40;i++){let h=1+i%11,m=[0,10,20,30,40,50][i%6],a=Math.abs(30*h-5.5*m);if(a>180)a=360-a;add('Clocks',i,`Find the smaller angle between the hands at ${h}:${String(m).padStart(2,'0')}.`,fmt(a),`Angle = |30H − 5.5M| = ${fmt(a)}°.`,'The hour hand moves 0.5° per minute.',choices(a,5),'If angle exceeds 180°, subtract from 360°.')}
const correct=['Each of the players has a locker.','Neither answer is correct.','She is senior to me.','The committee has submitted its report.'];for(let i=1;i<=40;i++){let c=correct[i%4];add('Verbal Reasoning',i,'Choose the grammatically correct sentence.',c,'This option follows standard agreement, pronoun, and preposition rules.','Check subject–verb agreement first.',[c,'Each of the players have a locker.','She is senior than me.','Neither answers are correct.'],'Eliminate obvious agreement errors.')}
const fact=n=>n<2?1:n*fact(n-1),days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
for(let i=1;i<=40;i++){let a=10+i,b=8+i%9,m=6+i%7,p=10000;add('Partnership',i,`A invests ₹${a}000 for 12 months and B ₹${b}000 for ${m} months. Divide a ₹${p} profit: find A's share.`,fmt(p*a*12/(a*12+b*m)),`Money-month ratio=${a*12}:${b*m}. A's share=${p}×${a*12}/${a*12+b*m}=₹${fmt(p*a*12/(a*12+b*m))}.`,'Profit follows capital multiplied by time.',choices(p*a*12/(a*12+b*m),100),'Compare money-months.')}
for(let i=1;i<=40;i++){let a=30+i%15,b=60+i%20,x=2+i%4,y=3+i%5,v=(a*x+b*y)/(x+y);add('Mixture & Alligation',i,`${x} kg at ₹${a}/kg is mixed with ${y} kg at ₹${b}/kg. Find mixture price/kg.`,fmt(v),`Total cost=₹${a*x+b*y}; quantity=${x+y} kg; price=₹${fmt(v)}/kg.`,'Use a weighted average.',choices(v,2),'Total cost ÷ total quantity.')}
for(let i=1;i<=40;i++){let a=10+i%10,b=15+i%12,t=a*b/(a+b);add('Pipes & Cisterns',i,`Inlets fill a tank in ${a} and ${b} hours. Find their combined time.`,fmt(t),`Rate=1/${a}+1/${b}; time=${a*b}/${a+b}=${fmt(t)} hours.`,'Add fractional filling rates.',choices(t,1),'For two inlets use ab/(a+b).')}
for(let i=1;i<=40;i++){let boat=10+i%12,s=1+i%5,d=boat+s,u=boat-s;add('Boats & Streams',i,`Downstream speed is ${d} km/h and upstream is ${u} km/h. Find still-water speed.`,boat,`Boat speed=(${d}+${u})/2=${boat} km/h.`,'Average downstream and upstream speeds.',null,'Boat=(D+U)/2.')}
for(let i=1;i<=40;i++){let n=30+i,start=i%7,ans=days[(start+n%7)%7];add('Calendar',i,`If today is ${days[start]}, what day is it after ${n} days?`,ans,`${n} mod 7=${n%7}; moving ${n%7} days gives ${ans}.`,'Reduce the interval modulo 7.',[ans,days[(start+1)%7],days[(start+2)%7],days[(start+3)%7]],'Only odd days matter.')}
for(let i=1;i<=40;i++){let n=4+i%5,r=2+i%3;r=Math.min(r,n);let v=fact(n)/fact(n-r);add('Permutation',i,`How many ordered arrangements of ${r} objects chosen from ${n} distinct objects?`,v,`${n}P${r}=${n}!/(${n-r})!=${v}.`,'Order matters.',null,'Cancel factorials early.')}
for(let i=1;i<=40;i++){let n=5+i%6,r=2+i%3,v=fact(n)/(fact(r)*fact(n-r));add('Combination',i,`How many committees of ${r} can be chosen from ${n} people?`,v,`${n}C${r}=${n}!/[${r}!${n-r}!] = ${v}.`,'Order does not matter.',null,'Use nCr=nC(n−r).')}
for(let i=1;i<=40;i++){let n=100+i*17,d=3+i%9,r=n%d;add('Number System',i,`Find the remainder when ${n} is divided by ${d}.`,r,`${n}=${d}×${Math.floor(n/d)}+${r}; remainder=${r}.`,'Remainder is less than divisor.',[r,(r+1)%d,(r+2)%d,d],'Find the nearest lower multiple.')}
for(let i=1;i<=40;i++){let d=[3,4,5,9][i%4],n=120+i*4;n-=n%d;add('Divisibility',i,`Which option is divisible by ${d}?`,n,`${n}/${d}=${n/d}, an integer.`,'Apply the divisibility rule.',[n,n+1,n+2,n+3],'Test digits before dividing.')}
for(let i=1;i<=40;i++){let a=10+i,b=3+i%7,c=2+i%5,v=a+b*c;add('Simplification',i,`Simplify ${a} + ${b} × ${c}.`,v,`BODMAS: ${b}×${c}=${b*c}; then ${a}+${b*c}=${v}.`,'Multiply before adding.',null,'Mark higher-priority operations.')}
for(let i=1;i<=40;i++){let n=2+i%14;add('Surds & Indices',i,`Simplify √${n*n}.`,n,`√${n*n}=${n}, the principal square root.`,'Recognize a perfect square.',[n,n+1,n-1,n*n],'Memorise common squares.')}
for(let i=1;i<=40;i++){let b=2+i%4,p=2+i%4,v=b**p;add('Logarithms',i,`Evaluate log base ${b} of ${v}.`,p,`${b}^${p}=${v}, hence log_${b}(${v})=${p}.`,'Express the argument as a power.',null,'Ask “base to what power?”')}
for(let i=1;i<=40;i++){let x=2+i,a=2+i%5,b=5+i%8,c=a*x+b;add('Algebra',i,`Solve ${a}x + ${b} = ${c}.`,x,`${a}x=${c-b}; x=${c-b}/${a}=${x}.`,'Isolate x.',null,'Undo addition, then multiplication.')}
for(let i=1;i<=40;i++){let a=30+i,b=60+i%30,c=180-a-b;add('Geometry',i,`A triangle has angles ${a}° and ${b}°. Find the third.`,c,`Third angle=180−${a}−${b}=${c}°.`,'Triangle angles total 180°.',null,'Subtract their sum from 180°.')}
for(let i=1;i<=40;i++){let x=10+i,ans='Statement I alone is sufficient';add('Data Sufficiency',i,`Find x. I: x=${x}. II: x is positive and below ${x+5}.`,ans,`I fixes one value, while II permits many; I alone is sufficient.`,'Test statements separately.',[ans,'II alone is sufficient','Both together are required','Data is insufficient'],'Do not solve beyond sufficiency.')}
for(let i=1;i<=40;i++){let a=40+i,b=25+i%10,x=10+i%8,v=a+b-x;add('Venn Diagrams',i,`${a} like Maths, ${b} English, ${x} both. How many like at least one?`,v,`Inclusion–exclusion: ${a}+${b}−${x}=${v}.`,'Subtract the overlap once.',null,'Union=A+B−intersection.')}
const rel=[['father','father'],['mother','mother'],['brother','brother'],['uncle','uncle']];for(let i=1;i<=40;i++){let r=rel[i%4][0];add('Blood Relations',i,`K is the ${r} of M. What is K's relation to M?`,r,`The statement directly says K is M's ${r}.`,'Read from K toward M.',[r,'cousin','sibling','grandparent'],'Draw generations and gender.')}
const ana=[['Bird','Nest','Bee','Hive'],['Doctor','Hospital','Teacher','School'],['Puppy','Dog','Kitten','Cat'],['Book','Read','Song','Listen']];for(let i=1;i<=40;i++){let x=ana[i%4];add('Analogy',i,`${x[0]}:${x[1]} :: ${x[2]}:?`,x[3],`${x[0]} relates to ${x[1]} in the same way ${x[2]} relates to ${x[3]}.`,'State the relationship.',[x[3],'Forest','Office','River'],'Match relationships, not appearance.')}
const odd=[['2','4','6','9','9'],['Triangle','Square','Circle','Cube','Cube'],['Rose','Lily','Lotus','Mango','Mango'],['January','March','July','Monday','Monday']];for(let i=1;i<=40;i++){let x=odd[i%4];add('Classification',i,`Find the odd one: ${x.slice(0,4).join(', ')}.`,x[4],`${x[4]} does not share the defining property of the other three.`,'Find the common category of three.',x.slice(0,4),'Check category, parity, or dimension.')}
for(let i=1;i<=40;i++){let n=30+i,t=5+i%15,v=n-t+1;add('Ranking',i,`Among ${n} students, A is ${t}th from top. Rank from bottom?`,v,`${n}−${t}+1=${v}.`,'Add one because A appears in both counts.',null,'Opposite rank=total−rank+1.')}
for(let i=1;i<=40;i++){let n=4+i%5,v=fact(n-1);add('Seating Arrangement',i,`How many circular arrangements of ${n} distinct people?`,v,`Circular arrangements=(${n}−1)!=${v}.`,'Fix one person.',null,'Arrange the remaining n−1 people.')}
for(let i=1;i<=40;i++){let a=2+i,d=3+i%5,v=a+4*d;add('Puzzle Solving',i,`Complete: ${a}, ${a+d}, ${a+2*d}, ${a+3*d}, ?`,v,`Common increase=${d}; next=${v}.`,'Inspect consecutive differences.',null,'Test the simplest consistent pattern first.')}
for(let i=1;i<=40;i++)add('Logical Reasoning',i,'All engineers are graduates. Some analysts are engineers. What follows?','Some analysts are graduates','Analysts who are engineers belong to the graduate set, so some analysts are graduates.','Use only necessary conclusions.',['Some analysts are graduates','All graduates are analysts','No analyst is a graduate','All analysts are engineers'],'Draw nested sets; never reverse “all”.')
for(let i=1;i<=40;i++){let n=3+i%5;add('Non-Verbal Reasoning',i,`A shape sequence adds one side each step. What follows a ${n}-sided shape?`,n+1,`The visual rule adds one side: ${n}+1=${n+1}.`,'Track the changing visual feature.',null,'Check sides, rotation, shade, and position.')}
for(let i=1;i<=40;i++)add('Critical Reasoning',i,'Sales rose after an ad campaign. Which conclusion is safest?','The campaign correlates with the rise but causation is unproven','Timing shows correlation, but other causes remain possible.',['Separate correlation from causation.'],['The campaign correlates with the rise but causation is unproven','Advertising always raises sales','The campaign definitely caused it','Sales never change naturally'],'Test alternative explanations.')
for(let i=1;i<=40;i++){let a=20+i,b=5+i%8;add('Quantitative Aptitude',i,`A test gives ${a} marks in A and ${b} in B. Find total.`,a+b,`Total=${a}+${b}=${a+b}.`,'Add both sections.',null,'Estimate before adding.')}
for(let i=1;i<=40;i++){let n=10+i,v=n*(n+1)/2;add('Arithmetic',i,`Sum the first ${n} natural numbers.`,v,`n(n+1)/2=${n}×${n+1}/2=${v}.`,'Use the sum formula.',null,'Pair first and last.')}
for(let i=1;i<=40;i++){let a=20+i,b=15+i%10,x=5+i%7,v=a+b-x;add('Modern Math',i,`${a} choose X, ${b} choose Y, ${x} choose both. How many choose X or Y?`,v,`${a}+${b}−${x}=${v}.`,'Use inclusion–exclusion.',null,'Subtract overlap once.')}
for(let i=1;i<=40;i++){let ns=[i,i+2,i+4,i+6,i+8];add('Basic Statistics',i,`Find the mean of ${ns.join(', ')}.`,i+4,`Sum=${ns.reduce((a,b)=>a+b)}; divide by 5 to get ${i+4}.`,'Mean=sum/count.',null,'Middle equals mean for symmetric data.')}
for(let i=1;i<=40;i++){let p=100+i*10,r=10+i%6*5,v=p*(100-r)/100;add('Frequently Asked',i,`₹${p} marked price has ${r}% discount. Find sale price.`,v,`${p}×${100-r}/100=₹${v}.`,'Use the remaining percentage.',null,'Multiply by (100−discount)/100.')}
for(const topic of new Set(bank.map(q=>q.topic))){bank.filter(q=>q.topic===topic).forEach((q,j)=>q.kind=j<20?'Solved Example':'Practice')}
const modelCatalog=['Direct computation','Reverse value','Missing base','Successive change','Comparison trap','Ratio form','Weighted result','Replacement cycle','Unit conversion','Work-rate model','Speed-time model','Table lookup','Chart comparison','Multi-step word problem','Maximum / minimum','Least / greatest value','Remainder cycle','Divisibility test','Factorisation','Approximation','Options elimination','Boundary case','Case split','Contradiction check','Statement I test','Statement II test','Combined statements','Counting restriction','Circular arrangement','Complement method','Pattern: differences','Pattern: ratios','Pattern: alternating','Pattern: squares / cubes','Inference from facts','Assumption check','Cause vs correlation','Grammar agreement','Vocabulary in context','Mixed placement challenge'];
for(const topic of new Set(bank.map(q=>q.topic))){bank.filter(q=>q.topic===topic).forEach((q,j)=>{q.model=modelCatalog[j%modelCatalog.length];q.topicLabel=topic;q.steps=(q.solution||'').split(/[.;]/).map(x=>x.trim()).filter(Boolean).slice(0,4)})}
window.questionBank=bank;
})();
